---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  stylelint:
    enabled: true
ratings:
  paths:
  - "**/*.scss"
  - "**/*.js"
exclude_paths:
- dist/
- node_modules/
- bower_components/
- gulpfile.js
- .idea/
- .tmp/
