linters:
  BorderZero:
    enabled: true
  ColorKeyword:
    enabled: true
  ColorVariable:
    enabled: true
  Comment:
    enabled: true
  FinalNewline:
    enabled: true
  IdSelector:
    enabled: true
  ImportPath:
    enabled: true
  ImportantRule:
    enabled: true
  Indentation:
    enabled: true
  LeadingZero:
    enabled: true
  MergeableSelector:
    enabled: true
  NameFormat:
    enabled: true
  NestingDepth:
    enabled: true
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: true
  QualifyingElement:
    enabled: true
  SelectorDepth:
    enabled: true
  Shorthand:
    enabled: true
  SingleLinePerSelector:
    enabled: false
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  StringQuotes:
    enabled: true
  TrailingSemicolon:
    enabled: true
  UnnecessaryMantissa:
    enabled: true
  UrlQuotes:
    enabled: true
